remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: "My Personal Website"
description: "Welcome to my page!"
theme: minima
author:
  name: Your Name
  email: your@email.com
